### ISSUE TITLE
context_db rollback when response is 204

### ISSUE THREAD

**Issue by relax-admin** [pangpanglabs/goutils#5]
context_db rollback when response is 204

goutils/echomiddleware/context_db.go

When the delete or put data, if successful will return 204, this time will enter this method, resulting in data rollback

**raw source：**
		if err := next(c); err != nil {
					session.Rollback()
					return err
				}
**idea：**
				if err := next(c); err != nil {
					if err.Error() != "http: request method or response status code does not allow body" { //http.StatusNoContent
						session.Rollback()
						return err
					}
				}

**Comment by xiaoxinmiao** [comment]
Already processed on the client,like this

func ReturnApiSucc(c echo.Context, status int, result interface{}) error {
	if status == 204 {
		return c.NoContent(status)
	}
	return c.JSON(status, ApiResult{
		Success: true,
		Result:  result,
	})
}

**Comment by jaehue** [comment]
：+1:
