### ISSUE TITLE
remove go routine from redis method

### ISSUE THREAD

**Issue by relax-admin** [pangpanglabs/goutils#58]
Let the caller decide for himself whether to use the go routine, writing in the common method will make the go routine uncontrollable.

**Comment by jaehue** [comment]
In generally `LoadOrStore` method is used as synchronously.
Even if `setToRedis` take so much time, it should not influence to main logic. 
So I make it goroutine.

**Comment by relax-admin** [comment]
When an API needs to support high concurrency, perhaps we need to control the number of go routines,
http://marcio.io/2015/07/handling-1-million-requests-per-minute-with-golang/
We may add the go routine control to the outer layer, and the specific content logic does not use the go routine.
like this:
	limitContoller(//go routine
		func(){
		redisMethod()//sync method
		}
		)

**Comment by relax-admin** [comment]
I agree with your opinion,Please close this issue

**Comment by jaehue** [comment]
The problem of that article and `setToRedis` are different.
In that article, main feature is uploading to s3. And so many requests use this feature.
But `setToRedis` action will happen very occasionally. And mostly, this action take very short.

"upload to s3" action take very long time. And if so many requests use this feature, controlling goroutine is very important.
In our case, it is over engineering.
